version: '3.8'

services:
  aquavox:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["bun", "go"]

volumes:
  node_modules:
